
plugins:
  - jekyll-include-cache
  - jekyll-minifier

exclude:
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/

ignored_categories:
  - alerts
  - accessibility
  - mathematics
  - editing
  - comments
  - git
  - justify
  - household
  - hands
  - music
  - devices
  - email
  - faces
  - emotions
  - gambling
  - games
  - menu
  - moving
  - error
  - close
  - people
  - add
  - chain
  - cog
  - coding
  - camping
  - ufo
  - spinner
  - settings
  - halloween
  - images
  - business
  - cleaning
  - save
  - thumbtack
  - christmas

sass:
    style: compressed
